//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateMetaEnumsAndStructs {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenerateMetaEnumsAndStructs.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _dimensionLOD2
        ///_fakedGrassNormal
        ///_vecCollParams
        ///_vecVehColl0B
        ///_vecVehColl0M
        ///_vecVehColl0R
        ///_vecVehColl1B
        ///_vecVehColl1M
        ///_vecVehColl1R
        ///_vecVehColl2B
        ///_vecVehColl2M
        ///_vecVehColl2R
        ///_vecVehColl3B
        ///_vecVehColl3M
        ///_vecVehColl3R
        ///_vecVehCollB
        ///_vecVehCollM
        ///_vecVehCollR
        ///aabb
        ///AABB
        ///aAnchors
        ///AbilityType
        ///Acceleration_Delta
        ///AccelGrid
        ///accumulationBufferSampler0
        ///accumulationBufferSampler1
        ///Action
        ///ActivateVehicleSiren
        ///activeChangesetConditions
        ///activeShadowCascades
        ///adapDOFProj
        ///AdapLumSampler
        ///AdaptedLu [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string metanames {
            get {
                return ResourceManager.GetString("metanames", resourceCulture);
            }
        }
    }
}
